server:
  port: 8182

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ego?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ego.entity

dubbo:
  application:
    name: dubbo-provider
  scan:
    base-packages: com.ego.service
  registry:
    address: 127.0.0.1
    port: 2181
    protocol: zookeeper
    register: true
  protocol:
    name: dubbo
    port: 20880
    accesslog: true
  provider:
    retries: 1
    delay: -1

ftpclient:
  host: localhost
  port: 21
  username: geely
  password: geely
  basePath: /home/ftpuser/
  filePath: /